apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-application
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-application
  template:
    metadata:
      labels:
        app: example-application
    spec:
      containers:
      - image: gitopssoundmollycontainerregistry.azurecr.io/gitops-example-application:v1.0.0
        name: gitops-example-application
        ports:
        - containerPort: 8080
